In [148]:
import numpy as np
import pandas as pd
import math
from scipy.special import logit

In [132]:
df=pd.read_excel("2019_day_ru.xls")
data=df.iloc[4:25,50]
print(data)
maxV=data.max()
minV=data.min()
data=norm(data)

4     2.1598
5     2.1598
6     2.1701
7     2.1788
8     2.1727
9     2.1727
10    2.1727
11    2.1727
12     2.159
13    2.1569
14    2.1532
15    2.1503
16    2.1503
17    2.1503
18    2.1542
19    2.1571
20    2.1556
21    2.1546
22    2.1499
23    2.1499
24    2.1499
Name: Unnamed: 50, dtype: object


In [133]:
def norm(x, reverse=False):
    if reverse==True:
        return (x*(maxV-minV)+minV)
    return (x-minV)/(maxV-minV)

In [151]:
rows=[]
for i in range(13):
    buff=np.array([[data.iloc[i],data.iloc[i+1],data.iloc[i+2],data.iloc[i+3]]])
    rows.append(buff)
input=np.array(rows, dtype=float).reshape((13,4))
output=data.iloc[4:17].to_numpy().reshape((13,1))
print(input)
print(output)

[[0.34256055 0.34256055 0.69896194 1.        ]
 [0.34256055 0.69896194 1.         0.78892734]
 [0.69896194 1.         0.78892734 0.78892734]
 [1.         0.78892734 0.78892734 0.78892734]
 [0.78892734 0.78892734 0.78892734 0.78892734]
 [0.78892734 0.78892734 0.78892734 0.31487889]
 [0.78892734 0.78892734 0.31487889 0.24221453]
 [0.78892734 0.31487889 0.24221453 0.11418685]
 [0.31487889 0.24221453 0.11418685 0.01384083]
 [0.24221453 0.11418685 0.01384083 0.01384083]
 [0.11418685 0.01384083 0.01384083 0.01384083]
 [0.01384083 0.01384083 0.01384083 0.14878893]
 [0.01384083 0.01384083 0.14878893 0.24913495]]
[[0.7889273356401364]
 [0.7889273356401364]
 [0.7889273356401364]
 [0.7889273356401364]
 [0.3148788927335556]
 [0.24221453287196348]
 [0.11418685121106895]
 [0.013840830449825607]
 [0.013840830449825607]
 [0.013840830449825607]
 [0.14878892733563295]
 [0.2491349480968763]
 [0.19723183391003796]]


In [152]:
def nonlin(x, deriv=False):
    if(deriv==True):
        return(x*(1-x))
    return 1/(1+np.exp(-x))

In [153]:
syn0=2*np.random.random((4,8))-1
syn1=2*np.random.random((8,1))-1
for i in range(60000):
    l0=input
    l1=nonlin(np.dot(l0,syn0))
    l2=nonlin(np.dot(l1,syn1))
    l2_error=output-l2
    l2_delta=l2_error*nonlin(l2, True)
    l1_error=l2_delta.dot(syn1.T)
    l1_delta=l1_error*nonlin(l1, True)
    syn1=syn1+l1.T.dot(l2_delta)
    syn0=syn0+l0.T.dot(l1_delta)
    syn1=syn1.astype(float)
    syn0=syn0.astype(float)
print(math.sqrt(sum(((norm(output,reverse=True)-norm(l2, reverse=True))**2)/13)))
print(norm(l2, reverse=True))


0.0033635617036206046
[[2.17154873]
 [2.17083334]
 [2.16986568]
 [2.1669643 ]
 [2.16827396]
 [2.15654756]
 [2.15293754]
 [2.15112547]
 [2.15130428]
 [2.15135217]
 [2.15179607]
 [2.15509362]
 [2.15719173]]


C:\Users\Dell\AppData\Local\Temp\ipykernel_19028\3313319139.py:15: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  print(math.sqrt(sum(((norm(output,reverse=True)-norm(l2, reverse=True))**2)/13)))


In [160]:
valid=df.iloc[26:33,50].to_numpy()
print(valid)
validx=np.array([[2.1556, 2.1539, 2.1527, 2.1516],
        [2.1539, 2.1527, 2.1516, 2.1516],
        [2.1527, 2.1516, 2.1516, 2.1516]])
validy=np.array([[2.1516], [2.1516], [2.1523]])
validx=norm(validx)
l0=validx
l1=nonlin(np.dot(l0,syn0))
l2=nonlin(np.dot(l1,syn1))
l2=norm(l2, reverse=True)
print(l2)

[2.1556 2.1539 2.1527 2.1516 2.1516 2.1516 2.1523]
[[2.15236603]
 [2.15262719]
 [2.15287793]]
