In [ ]:
import numpy as np
import pandas as pd

In [7]:
data = {
    "Масса(т.)": [0.25, 0.75, 0.5, 1, 0.75, 1, 0.75, 0.75, 1],
    "Двигатель(л.с.)": [0.25, 0.75, 0.5, 1, 0.75, 0.75, 0.75, 0.75, 1],
    "Пассажиров(чел.)": [0.25, 0.75, 0.25, 0.25, 0.25, 1, 0.25, 0.25, 1],
    "Грузоподъёмн.(т.)": [0, 0.25, 0, 1, 0.25, 1, 0.5, 0, 1],
    "Type":[[1,0,0],[0,1,0],[1,0,0],[0,0,1],[0,0,1],[0,1,0],[0,0,1],[1,0,0],[0,1,0]]
}
index = ["Ока", "Газель пассажир.", "Лада Калина", "Камаз(3 оси)", "Газель груз.",
         "ПАЗ34234(пазик)", "ЗИЛ-5301(бычок)", "УАЗ Патриот", "ЛиАЗ-6213"]
df = pd.DataFrame(data, index=index)



In [6]:
X = df[["Масса(т.)", "Двигатель(л.с.)", "Пассажиров(чел.)", "Грузоподъёмн.(т.)"]].values
y = np.array(df["Type"].tolist())

print("Входные данные (X):")
print(X)
print("\nВыходные данные (y):")
print(y)

Входные данные (X):
[[0.25 0.25 0.25 0.  ]
 [0.75 0.75 0.75 0.25]
 [0.5  0.5  0.25 0.  ]
 [1.   1.   0.25 1.  ]
 [0.75 0.75 0.25 0.25]
 [1.   0.75 1.   1.  ]
 [0.75 0.75 0.25 0.5 ]
 [0.75 0.75 0.25 0.  ]
 [1.   1.   1.   1.  ]]

Выходные данные (y):
[[1 0 0]
 [0 1 0]
 [1 0 0]
 [0 0 1]
 [0 0 1]
 [0 1 0]
 [0 0 1]
 [1 0 0]
 [0 1 0]]


In [8]:
def nonlin(x, deriv=False):
    if(deriv==True):
        return(x*(1-x))
    return 1/(1+np.exp(-x))

In [16]:
syn0=2*np.random.random((4,3))-1
for i in range(10000):
    l0=X
    l1=nonlin(np.dot(l0,syn0))
    l1_error=y-l1
    l1_delta=l1_error*nonlin(l1, True)
    syn0=syn0+l0.T.dot(l1_delta)
    syn0=syn0.astype(float)
print(np.round(l1, 4))

[[0.8994 0.2051 0.0025]
 [0.0565 0.8766 0.    ]
 [0.9774 0.     0.0132]
 [0.     0.0494 1.    ]
 [0.0172 0.     0.9221]
 [0.     1.     0.01  ]
 [0.     0.0016 0.9995]
 [0.9952 0.     0.0665]
 [0.     1.     0.0297]]
