In [1]:
import numpy as np
import pandas as pd
import math

In [2]:
data = {
    "Здоровье": [0.5, 0.9, 0.8, 0.3, 0.6, 0.4, 0.9, 0.6, 0.1, 0.6, 1],
    "Пистолет": [1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0],
    "Враги": [0.14, 0.29, 0.14, 0.14, 0.29, 0.14, 1, 0.57, 0.14, 0, 0],
    "Действие":[[1,0,0,0],[1,0,0,0],[1,0,0,0],[0,1,0,0],[0,1,0,0],[0,1,0,0],[0,0,1,0],[0,0,1,0],[0,0,1,0],[0,0,0,1],[0,0,0,1]]
}
df = pd.DataFrame(data)
X = df[["Здоровье", "Пистолет", "Враги"]].values
y = np.array(df["Действие"].tolist())

print("Входные данные (X):")
print(X)
print("\nВыходные данные (y):")
print(y)

Входные данные (X):
[[0.5  1.   0.14]
 [0.9  1.   0.29]
 [0.8  0.   0.14]
 [0.3  1.   0.14]
 [0.6  1.   0.29]
 [0.4  0.   0.14]
 [0.9  1.   1.  ]
 [0.6  1.   0.57]
 [0.1  0.   0.14]
 [0.6  1.   0.  ]
 [1.   0.   0.  ]]

Выходные данные (y):
[[1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 1 0]
 [0 0 1 0]
 [0 0 0 1]
 [0 0 0 1]]


In [3]:
def nonlin(x, deriv=False):
    if(deriv==True):
        return(x*(1-x))
    return 1/(1+np.exp(-x))

In [20]:
syn0=2*np.random.random((3,4))-1
syn1=2*np.random.random((4,4))-1
for i in range(2000):
    l0=X
    l1=nonlin(np.dot(l0,syn0))
    l2=nonlin(np.dot(l1,syn1))
    l2_error=y-l2
    l2_delta=l2_error*nonlin(l2, True)
    l1_error=l2_delta.dot(syn1.T)
    l1_delta=l1_error*nonlin(l1, True)
    syn1=syn1+l1.T.dot(l2_delta)
    syn0=syn0+l0.T.dot(l1_delta)
    syn1=syn1.astype(float)
    syn0=syn0.astype(float)
print(np.round(l2, 3))

[[0.927 0.158 0.    0.006]
 [0.963 0.07  0.    0.   ]
 [0.987 0.037 0.    0.027]
 [0.054 0.872 0.005 0.   ]
 [0.001 0.896 0.045 0.   ]
 [0.033 0.875 0.016 0.   ]
 [0.    0.    0.997 0.   ]
 [0.    0.012 0.954 0.   ]
 [0.    0.128 0.996 0.   ]
 [0.057 0.047 0.    0.968]
 [0.028 0.016 0.    0.983]]
