In [6]:
import numpy as np
import pandas as pd
import math
import re

In [2]:
def nonlin(x, deriv=False):
    if (deriv == True):
        return (x * (1 - x))

    return 1 / (1 + np.exp(-x))

In [ ]:
def check_spam_features(text):
    uppercase_words = re.findall(r'\b[A-ZА-Я]{2,}\b', text)
    has_uppercase = 1 if uppercase_words else 0
    text_lower = text.lower()
    has_keywords = 1 if 'скидки' in text_lower or 'распродажа' in text_lower else 0
    return has_uppercase, has_keywords

In [20]:
X=[]
test_texts = [
    "СКИДКИ на все товары! РАСПРОДАЖА",
    "Привет, как дела?",
    "Большая РАСПРОДАЖА начинается завтра",
    "сегодня скидки на все",
    "Обычное предложение без акций",
    "ВНИМАНИЕ! важное объявление",
    "Скидки и распродажа целый месяц"
]
for text in test_texts:
    a = check_spam_features(text)
    X.append(a)
X=np.array(X)
print(X)
y=np.array([[1,0,1,1,0,1,1]]).T
print(y)

[[1 1]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [1 0]
 [0 1]]
[[1]
 [0]
 [1]
 [1]
 [0]
 [1]
 [1]]


In [25]:
syn0 = 2 * np.random.random((2, 2)) - 1
syn1 = 2 * np.random.random((2, 1)) - 1
for j in range(60000):
    l0=X
    l1=nonlin(np.dot(l0,syn0))
    l2=nonlin(np.dot(l1,syn1))
    l2_error=y-l2
    l2_delta=l2_error*nonlin(l2, True)
    l1_error=l2_delta.dot(syn1.T)
    l1_delta=l1_error*nonlin(l1, True)
    syn1=syn1+l1.T.dot(l2_delta)
    syn0=syn0+l0.T.dot(l1_delta)
    syn1=syn1.astype(float)
    syn0=syn0.astype(float)
print(l2)

[[0.99797373]
 [0.00505089]
 [0.99797373]
 [0.99720059]
 [0.00505089]
 [0.99676888]
 [0.99720059]]
